<a href="https://colab.research.google.com/github/lippek/datasciencebotcamp/blob/master/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.18.4'

In [0]:
x = np.array([1,3])
x

In [0]:
x.shape

(2,)

In [0]:
x.size

2

In [0]:
x.dtype

dtype('int64')

In [0]:
x = np.array([1.3,2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [0]:
x = np.array([[1,2], [-3,1]])

In [0]:
x.shape

(2, 2)

In [0]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
     [[4,3,1],
      [3,1,2]]]
     
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 3, 1],
        [3, 1, 2]]])

In [0]:
a = np.array([1,2,3], dtype = 'float')
a.dtype

dtype('float64')

In [0]:
a = np.array([1.3,2.3, 1.4], dtype='int')
a

array([1, 2, 1])

In [0]:
np.zeros(shape = (4,10), dtype = 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [0]:
np.ones(shape = (5,5), dtype = 'int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [0]:
np.full(shape = (3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [0]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(start =100 , stop = 10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [0]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
A.reshape((-1,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])

In [0]:
A + B

array([6, 0, 7, 4])

In [0]:
x = np.array([[1,3], [-2, 0]])
y = np.array([[6,0], [-1, 2]])
x
y

array([[ 6,  0],
       [-1,  2]])

In [0]:
np.dot(x,y)

array([[  3,   6],
       [-12,   0]])

In [0]:
np.random.seed(0)

In [0]:
np.random.randn(10,4)

array([[ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351,  0.76103773],
       [ 0.12167502,  0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575],
       [-1.98079647, -0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275, -1.04855297]])

In [0]:
np.random.rand(10,10)

array([[0.11037514, 0.65632959, 0.13818295, 0.19658236, 0.36872517,
        0.82099323, 0.09710128, 0.83794491, 0.09609841, 0.97645947],
       [0.4686512 , 0.97676109, 0.60484552, 0.73926358, 0.03918779,
        0.28280696, 0.12019656, 0.2961402 , 0.11872772, 0.31798318],
       [0.41426299, 0.0641475 , 0.69247212, 0.56660145, 0.26538949,
        0.52324805, 0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609, 0.18319136,
        0.58651293, 0.02010755, 0.82894003, 0.00469548, 0.67781654],
       [0.27000797, 0.73519402, 0.96218855, 0.24875314, 0.57615733,
        0.59204193, 0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782, 0.39650574,
        0.8811032 , 0.58127287, 0.88173536, 0.69253159, 0.72525428],
       [0.50132438, 0.95608363, 0.6439902 , 0.42385505, 0.60639321,
        0.0191932 , 0.30157482, 0.66017354, 0.29007761, 0.61801543],
       [0.4287687 , 0.13547406, 0.2982823

In [0]:
np.random.randint(low = 10, high = 100, size = 10)

array([60, 13, 41, 19, 20, 37, 55, 81, 49, 71])

In [0]:
np.random.choice([4,2,1,3])

2

In [0]:
data = np.random.rand(10)
data

array([0.74999925, 0.33940382, 0.48954894, 0.33898512, 0.17949026,
       0.1709866 , 0.46345098, 0.87457296, 0.94411975, 0.60825287])

In [0]:
np.random.shuffle(data)

In [0]:
np.exp(1)

2.718281828459045

In [0]:
np.any([1,2,1])

True

In [0]:
bool(1.3)

True

In [0]:
a = np.random.rand(5)
a

array([0.96448977, 0.55424244, 0.2123905 , 0.22244322, 0.21874937])

In [0]:
np.argmax(a)

0

In [0]:
a[np.argmax(a)]

0.9644897677894309

In [0]:
np.argsort(a,)

array([2, 4, 3, 1, 0])

In [3]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [6]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [19]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [27]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [32]:
A = np.arange(start = -10, stop = 10, step = 0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [33]:
A >0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [39]:
np.bitwise_and(A > 0, A < 5, A > 1)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])