<a href="https://colab.research.google.com/github/lippek/datasciencebotcamp/blob/master/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
v1 = np.array([-1,4])

In [0]:
np.linalg.norm(v1)

4.123105625617661

In [0]:
v2 = np.array([-10, 10, 13])

In [0]:
np.linalg.norm(v2)

19.209372712298546

In [0]:
x = np.array([[5,3], [3, 9]])
y = np.array([[1], [-1]])

print(x)
print(y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [0]:
z = np.eye(5, dtype = 'int')
z


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [0]:
x
b = np.linalg.inv(x)
b


array([[ 0.25      , -0.08333333],
       [-0.08333333,  0.13888889]])

In [2]:
a = np.array([[2,4],[1,-1]])
a

array([[ 2,  4],
       [ 1, -1]])

In [4]:
b = np.array([[10],[-1]])
b

array([[10],
       [-1]])

In [0]:
a_inv = np.linalg.inv(a)
x = np.dot(a_inv, b)

In [8]:
x

array([[1.],
       [2.]])